import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import { getSession } from "next-auth/client"
import Login from '../components/Login'

export default function Home({ session }) {

  if (!session) {
    return <Login />;
  }

  return (
    <div>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <main>
        {/* Sidebar */}

        {/* Feed */}

        {/* Widgets */}
      </main>

    </div>
  )
}

export async function getServerSideProps(context) {
  //get the user
  const session = await getSession(context);

  return {
    props: {
      session
    }, // will be passed to the page component as props
  }
}